Added more dependency list.

diff --git a/butler b/butler
--- a/butler
+++ b/butler
@@ -77,10 +77,9 @@ butlerrun() {
             fi
         done
         if [ ${#reqdeps} != 0 ]; then # If the user needs to install any dependencies, try to get the user to install them.
-            butlermsg "The task \"$name\" requires ${#reqdeps[@]} more dependencies..."
+            butlermsg "${depnum} dependencies found. Task \"$name\" needs ${#reqdeps[@]} more dependencies..."
             sudo pacman -S ${reqdeps[@]}
-            if [ $? != 0 ]; then # If the pacman process did not successfully run, do not continue.
-                butlermsg "Package transfer failed. Not running task."
+            if [ $? != 0 ]; then # If the pacman process did not successfully run, do not continue.  butlermsg "Package transfer failed. Not running task."
                 exit
             fi
         fi
@@ -95,10 +94,10 @@ butlermsg() {
     # Displays the requested message according to the user's settings
     echo -e "\033[01;36m[❖ BUTLER]\033[0m $1"
     if [ "$enable_notifications" == "true" ]; then
-	notify-send -u low "Sapphire Butler" "$1"
+	    notify-send -u low "Sapphire Butler" "$1"
     fi
     if [ "$enable_espeak" == "true" ]; then
-	espeak "$1" # "Cool" haxor kids use espeak.
+	    espeak "$1" # "Cool" haxor kids use espeak.
     fi
 }
 
@@ -122,7 +121,7 @@ if [ -n "$1" ]; then
             done
         else
 	    # The user did not supply a department or task, so check if the user supplied only a task name without the department
-            didyoumean=$(find "/usr/share/sapphire-butler/departments/" -name "$tasktodo" &> /dev/null | sed 's/\/usr\/share\/sapphire-butler\/departments\///g')
+        didyoumean=$(find "/usr/share/sapphire-butler/departments/" -name "$tasktodo" | sed 's/\/usr\/share\/sapphire-butler\/departments\///g')
 	    # If the user supplied a task name without the department, recommend them to run it with the department
         # Actually we just run that task we found because why not.
 	    if [ -f "/usr/share/sapphire-butler/departments/$didyoumean/task.sh" ]; then
